### PR TITLE
add support for ghc-8.10

### LINKED ISSUE #2: ghc-8.10 support
I found out on [matrix.haskell.org](https://matrix.hackage.haskell.org/#/package/typelevel-rewrite-rules) that typelevel-rewrite-rules doesn't build with ghc-8.10; I published a revision adding an upper-bound of `ghc < 8.10`, but the real fix is to make the code work with ghc-8.10.

### PR DESCRIPTION
**Pull request by gelisam**
since I've had to change a bunch of imports, this probably breaks for
older GHCs, but let's wait for CI to confirm this before bumping the
lower bound.

Fixes #2

### CODE REVIEW

**Comment by gelisam** [comment]
CC @tscholak

**Comment by gelisam** [comment]
Hmm, Travis is taking forever to start the CI builds, and they don't say why, it just says "Queued". Have I [ran out of credits already](https://github.com/gelisam/typelevel-rewrite-rules/issues/11)? I don't remember running anything in Travis this month. And I can't even figure out how to see how many credits I have left! What a terrible UI.

I guess I'll run the tests manually on my machine.

**Comment by gelisam** [comment]
As I suspected, the code no longer compiles with ghc-8.8 and earlier. Gotta bump those lower bounds!

**Comment by tscholak** [comment]
Awesome, thanks @gelisam !

**Pull request merged**
